# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/logo-dataizer',
                'doc_host': 'https://davegrays.github.io',
                'git_url': 'https://github.com/davegrays/logo-dataizer',
                'lib_path': 'logo_dataizer'},
  'syms': {'logo_dataizer.core': {'logo_dataizer.core.foo': ('core.html#foo', 'logo_dataizer/core.py')}}}
